"""Embedded auth scaffolding for Vibrant."""

from .auth import (
    AccessTokenBundle,
    AuthStore,
    AuthUser,
    AuthorizationCodeGrant,
    AuthorizationDecision,
    AuthorizationRequest,
    AuthorizationServerService,
    HMACTokenSigner,
    InMemoryAuthStore,
    OAuthClient,
    OAuthError,
    ScopeResolutionError,
    TokenExchangeRequest,
    build_s256_code_challenge,
    create_auth_app,
    expand_role_scopes,
    normalize_scopes,
    resolve_scopes,
    scope_string,
)
from .authz import (
    ADMIN_SCOPE,
    MCP_ACCESS_SCOPE,
    TASKS_READ_SCOPE,
    TASKS_RUN_SCOPE,
    TASKS_WRITE_SCOPE,
    default_role_scopes,
)
from .config import OAuthServerSettings

__all__ = [
    "ADMIN_SCOPE",
    "AccessTokenBundle",
    "AuthStore",
    "AuthUser",
    "AuthorizationCodeGrant",
    "AuthorizationDecision",
    "AuthorizationRequest",
    "AuthorizationServerService",
    "HMACTokenSigner",
    "InMemoryAuthStore",
    "MCP_ACCESS_SCOPE",
    "OAuthClient",
    "OAuthError",
    "OAuthServerSettings",
    "ScopeResolutionError",
    "TASKS_READ_SCOPE",
    "TASKS_RUN_SCOPE",
    "TASKS_WRITE_SCOPE",
    "TokenExchangeRequest",
    "build_s256_code_challenge",
    "create_auth_app",
    "default_role_scopes",
    "expand_role_scopes",
    "normalize_scopes",
    "resolve_scopes",
    "scope_string",
]
