"""Policy-layer command and query contracts."""

from __future__ import annotations

from typing import Protocol

from ..types import WorkflowSnapshot
from .gatekeeper_loop.models import GatekeeperLoopState
from .task_loop.models import TaskLoopSnapshot


class PolicyCommandPort(Protocol):
    async def submit_user_input(self, text: str, question_id: str | None = None): ...
    async def restart_gatekeeper(self, reason: str | None = None): ...
    async def stop_gatekeeper(self): ...
    async def run_next_task(self): ...
    async def run_until_blocked(self): ...


class PolicyQueryPort(Protocol):
    def workflow_snapshot(self) -> WorkflowSnapshot: ...
    def gatekeeper_state(self) -> GatekeeperLoopState: ...
    def task_loop_state(self) -> TaskLoopSnapshot: ...
